name: DULMS Auto Tracker

on:
  schedule:
    - cron: '0 */4 * * *' # يشتغل كل 4 ساعات
  workflow_dispatch:

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Tracker Script
      env:
        STUDENT_ID: ${{ secrets.STUDENT_ID }}
        STUDENT_PASS: ${{ secrets.STUDENT_PASS }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python main.py

    - name: Save Absence Memory
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add absence_data.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update absence memory" && git push)
